apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-service-b
  labels:
    app: worker-service-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-service-b
  template:
    metadata:
      labels:
        app: worker-service-b
    spec:
      containers:
        - name: worker-service-b
          image: seu-registro/worker-service:latest
          imagePullPolicy: Always
          env:
            - name: WORKER_NAME
              value: "WorkerServiceB" # Define o nome do worker aqui
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"