apiVersion: batch/v1
kind: CronJob
metadata:
  name: worker-service-b-cron
  labels:
    app: worker-service-b
spec:
  schedule: "0 6 * * *"  # Agendado para rodar todos os dias às 06:00
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: worker-service-b
        spec:
          containers:
            - name: worker-service-b
              image: seu-registro/worker-service-b:latest
              env:
                - name: WORKER_NAME
                  value: "WorkerServiceB"
                - name: HORARIO
                  value: "22:00"
          restartPolicy: OnFailure