apiVersion: batch/v1
kind: CronJob
metadata:
  name: worker-service-a-cron
  labels:
    app: worker-service-a
spec:
  schedule: "0 0 * * *"  # Agendado para rodar todos os dias à meia-noite
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: worker-service-a
        spec:
          containers:
            - name: worker-service-a
              image: seu-registro/worker-service-a:latest
              env:
                - name: WORKER_NAME
                  value: "WorkerServiceA"
                - name: HORARIO
                  value: "20:00"
          restartPolicy: OnFailure